Test

In [ ]:
import pandas as pd
import numpy as np
import os

In [93]:
# Code that sets up file paths for raw and processed data

PROJECT_ROOT = os.path.abspath("..")

RAW_DATA_DIR = os.path.join(PROJECT_ROOT, "data", "raw")
PROCESSED_DATA_DIR = os.path.join(PROJECT_ROOT, "data", "processed")

# Some example file paths for now
tech_path = os.path.join(RAW_DATA_DIR, "nyse etfs", "2", "xlk.us.txt") 
energy_path = os.path.join(RAW_DATA_DIR, "nyse etfs", "2", "xle.us.txt")

securities = [tech_path, energy_path]

os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)

print(f"Project Root:   {PROJECT_ROOT}")
print(f"Raw Tech Data:  {tech_path}")
print(f"Processed Dir:  {PROCESSED_DATA_DIR}")

Project Root:   /Users/wilbur_elb/git/Sector-Analysis
Raw Tech Data:  /Users/wilbur_elb/git/Sector-Analysis/data/raw/nyse etfs/2/xlk.us.txt
Processed Dir:  /Users/wilbur_elb/git/Sector-Analysis/data/processed

In [154]:
def load_stooq_data(filepath):
    if not os.path.exists(filepath):
        print(f"Error: File not found at {filepath}")
        return None

    df = pd.read_csv(filepath)

    df.columns = [c.lower().strip('<>') for c in df.columns]

    df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')

    df.set_index('date', inplace=True)

    df.sort_index(inplace=True)
    
    df['ticker'] = df['ticker']
    
    return df

In [164]:
for security in securities:
    df = load_stooq_data(security)
    print(f"**Cleaned Data Preview For {security}**")
    display(df.head())
    print("-"*100)

**Cleaned Data Preview For /Users/wilbur_elb/git/Sector-Analysis/data/raw/nyse etfs/2/xlk.us.txt**

,ticker,per,time,open,high,low,close,vol,openint
date,,,,,,,,,
2005-02-25,XLK.US,D,0,8.14276,8.20781,8.12124,8.18729,1411402,0
2005-02-28,XLK.US,D,0,8.17191,8.24455,8.13492,8.16353,2063458,0
2005-03-01,XLK.US,D,0,8.22374,8.27865,8.19992,8.26213,1457586,0
2005-03-02,XLK.US,D,0,8.21540,8.30192,8.18335,8.24021,1103946,0
2005-03-03,XLK.US,D,0,8.22768,8.26547,8.14700,8.17950,983216,0

----------------------------------------------------------------------------------------------------
**Cleaned Data Preview For /Users/wilbur_elb/git/Sector-Analysis/data/raw/nyse etfs/2/xle.us.txt**

,ticker,per,time,open,high,low,close,vol,openint
date,,,,,,,,,
2005-02-25,XLE.US,D,0,13.0063,13.3401,12.9765,13.2739,22725659,0
2005-02-28,XLE.US,D,0,13.3730,13.4470,12.7444,13.1787,31526166,0
2005-03-01,XLE.US,D,0,13.1475,13.2233,12.9050,12.9226,24827621,0
2005-03-02,XLE.US,D,0,12.8695,13.1362,12.8383,13.1120,20350172,0
2005-03-03,XLE.US,D,0,13.1631,13.3549,13.1475,13.3284,32823544,0

----------------------------------------------------------------------------------------------------